name: Build and Deploy Flutter Web App

permissions:
    actions: write
    pages: write

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Flutter Web
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: flutter_skeleton/pubspec.yaml # path to pubspec.yaml
      - run: flutter --version

      - name: Navigate to Flutter App Directory
        working-directory: flutter_skeleton
        run: flutter pub get

      - name: Build Flutter Web
        working-directory: flutter_skeleton
        run: flutter build web --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: flutter_skeleton/build/web
        #   personal_token: ${{ secrets.PERSONAL_TOKEN }}
        #   external_repository: BorderBook/borderbook.github.io
        #   publish_branch: main
